AllCops:
  Exclude:
    - "README.md"
    - "Guardfile"
    - "Rakefile"

  DisplayCopNames: true

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 50
Metrics/ClassLength:
  Max: 200
Metrics/BlockLength:
  ExcludedMethods: ['describe']
  Max: 30


Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: true
Style/EachForSimpleLoop:
  Enabled: true
Style/AndOr:
  Enabled: true
Style/DefWithParentheses:
  Enabled: true
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Layout/HashAlignment: true
  EnforcedColonStyle: key
Layout/ExtraSpacing: true
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation: true
  Enabled: true
  EnforcedStyle: indented